# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{autotest-diff}
  s.version = "0.1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David J. Hamilton"]
  s.date = %q{2011-04-13}
  s.description = %q{
      autotest-diff is an autotest style for rspec2 or rspec2 rails that tries
      not to run specs you aren't working on.

      It is obviously most helpful when you have slow-running specs, as is often
      the case when working on a rails app, for instance.

      When autotest decides to run multiple test files, autotest-diff behaves
      just as rspec's style.  When running only a single file, autotest-diff
      compares the current file against a cached copy.  
      
      If there is no cached copy, all examples are run.
      
      If there is a cached copy, only the examples that are modified are run.
      This is done by passing --line_number flags to rspec.

      autotest-diff has a very simple implementation, and depends on diff and
      sed being in your $PATH.  autotest-diff is not expected to work on windows.
    }
  s.email = %q{autotest-diff@hjdivad.com}
  s.files = [
    ".autotest",
    ".rspec",
    "Gemfile",
    "Rakefile",
    "VERSION.yml",
    "autotest-diff.gemspec",
    "lib/autotest/auto_diff.rb",
    "lib/autotest/autodiff_rails_rspec2.rb",
    "lib/autotest/autodiff_rspec2.rb",
    "lib/autotest/discover.rb",
    "spec/autotest/autodiff_rspec2_spec.rb",
    "spec/fixtures/no-cache/spec/new_lines_spec.rb",
    "spec/fixtures/with-cache/.autodiff/cache/spec/changed_lines_multiple_examples_spec.rb",
    "spec/fixtures/with-cache/.autodiff/cache/spec/changed_lines_spec.rb",
    "spec/fixtures/with-cache/.autodiff/cache/spec/new_lines_spec.rb",
    "spec/fixtures/with-cache/spec/changed_lines_multiple_examples_spec.rb",
    "spec/fixtures/with-cache/spec/changed_lines_spec.rb",
    "spec/fixtures/with-cache/spec/new_lines_spec.rb",
    "spec/integration/autotest/autodiff_rspec2_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/fixtures.rb",
    "spec/support/matchers/file_exists.rb",
    "spec/support/matchers/line_numbers.rb",
    "spec/support/rspec.rb"
  ]
  s.homepage = %q{http://github.com/hjdivad/autotest-diff}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Autotest style that only runs rspec examples within a spec that have changed.}
  s.test_files = [
    "spec/autotest/autodiff_rspec2_spec.rb",
    "spec/fixtures/no-cache/spec/new_lines_spec.rb",
    "spec/fixtures/with-cache/spec/changed_lines_multiple_examples_spec.rb",
    "spec/fixtures/with-cache/spec/changed_lines_spec.rb",
    "spec/fixtures/with-cache/spec/new_lines_spec.rb",
    "spec/integration/autotest/autodiff_rspec2_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/fixtures.rb",
    "spec/support/matchers/file_exists.rb",
    "spec/support/matchers/line_numbers.rb",
    "spec/support/rspec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec-core>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<autotest>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<project>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_runtime_dependency(%q<rspec-core>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<autotest>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<project>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
    else
      s.add_dependency(%q<rspec-core>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<autotest>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<project>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<rspec-core>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<autotest>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<project>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec-core>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<autotest>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<project>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<rspec-core>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<autotest>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<project>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
  end
end

